---

- name: Install Etherpad node modules locally
  npm:
    global: no
    path: "{{ nodejs_app_install_dir }}"
    name: "{{ item }}"
  with_items:
    - "{{ etherpad_npm_packages }}"

- name: Set Etherpad settings file
  template:
    dest: "{{ nodejs_app_install_dir }}/settings.json"
    src: settings.json.template
  notify: Restart the application systemd unit

- name: Remove lock file if exists
  file:
    path: "{{ nodejs_app_install_dir  }}/src/.ep_initialized"
    state: absent

